In [1]:
import pandas as pd
import tpqoa as tpqoa

**Streaming Tick or Live Data**

In [2]:
api = tpqoa.tpqoa("D:\\Dissertation Mohit\\src\\oanda.cfg")

In [3]:
api.stream_data("EUR_USD", stop=10)

2026-03-13T15:04:14.100448597Z 1.14571 1.14579
2026-03-13T15:04:17.993294871Z 1.14568 1.14578
2026-03-13T15:04:18.074013914Z 1.14568 1.14577
2026-03-13T15:04:18.443582163Z 1.14568 1.14577
2026-03-13T15:04:18.644486838Z 1.14567 1.14576
2026-03-13T15:04:19.498981195Z 1.14569 1.14577
2026-03-13T15:04:19.725399385Z 1.14568 1.14577
2026-03-13T15:04:20.201812524Z 1.14568 1.14576
2026-03-13T15:04:20.341795731Z 1.14568 1.14576
2026-03-13T15:04:21.004405165Z 1.14567 1.14576

**Orders and trades**

In [4]:
api.create_order("EUR_USD", 100000)

 {'id': '669', 'time': '2026-03-13T15:04:21.751397363Z', 'userID': 36234373, 'accountID': '101-004-36234373-001', 'batchID': '668', 'requestID': '115524629585519060', 'type': 'ORDER_FILL', 'orderID': '668', 'instrument': 'EUR_USD', 'units': '100000.0', 'gainQuoteHomeConversionFactor': '0.75069128198', 'lossQuoteHomeConversionFactor': '0.75823591798', 'price': 1.14573, 'fullVWAP': 1.14573, 'fullPrice': {'type': 'PRICE', 'bids': [{'price': 1.14565, 'liquidity': '500000'}, {'price': 1.14564, 'liquidity': '500000'}, {'price': 1.14563, 'liquidity': '2000000'}, {'price': 1.14562, 'liquidity': '2000000'}, {'price': 1.14561, 'liquidity': '5000000'}, {'price': 1.14559, 'liquidity': '10000000'}, {'price': 1.14556, 'liquidity': '10000000'}], 'asks': [{'price': 1.14573, 'liquidity': '500000'}, {'price': 1.14575, 'liquidity': '2500000'}, {'price': 1.14576, 'liquidity': '2000000'}, {'price': 1.14577, 'liquidity': '5000000'}, {'price': 1.1458, 'liquidity': '10000000'}, {'price': 1.14583, 'liquidity': '10000000'}], 'closeoutBid': 1.14556, 'closeoutAsk': 1.14583}, 'reason': 'MARKET_ORDER', 'pl': '0.0', 'financing': '0.0', 'commission': '0.0', 'guaranteedExecutionFee': '0.0', 'accountBalance': '202873.9829', 'tradeOpened': {'tradeID': '669', 'units': '100000.0', 'price': 1.14573, 'guaranteedExecutionFee': '0.0', 'halfSpreadCost': '3.0179', 'initialMarginRequired': '2881.3333'}, 'halfSpreadCost': '3.0179'}

In [5]:
api.get_positions()

[{'instrument': 'EUR_USD',
  'pl': '2941.6155',
  'unrealizedPL': '-6.0659',
  'marginUsed': '2881.3333',
  'resettablePL': '2941.6155',
  'financing': '22.2609',
  'commission': '0.0',
  'guaranteedExecutionFees': '0.0',
  'long': {'units': '100000.0',
   'averagePrice': 1.14573,
   'tradeIDs': ['669'],
   'pl': '-620.4904',
   'unrealizedPL': '-6.0659',
   'resettablePL': '-620.4904',
   'financing': '-34.6016',
   'guaranteedExecutionFees': '0.0'},
  'short': {'units': '0.0',
   'pl': '3562.1059',
   'unrealizedPL': '0.0',
   'resettablePL': '3562.1059',
   'financing': '56.8625',
   'guaranteedExecutionFees': '0.0'}}]

In [6]:
api.create_order("EUR_USD", -100000)

 {'id': '671', 'time': '2026-03-13T15:04:22.064084110Z', 'userID': 36234373, 'accountID': '101-004-36234373-001', 'batchID': '670', 'requestID': '115524629589714128', 'type': 'ORDER_FILL', 'orderID': '670', 'instrument': 'EUR_USD', 'units': '-100000.0', 'gainQuoteHomeConversionFactor': '0.750688449707', 'lossQuoteHomeConversionFactor': '0.758233057241', 'price': 1.14565, 'fullVWAP': 1.14565, 'fullPrice': {'type': 'PRICE', 'bids': [{'price': 1.14565, 'liquidity': '500000'}, {'price': 1.14564, 'liquidity': '500000'}, {'price': 1.14563, 'liquidity': '2000000'}, {'price': 1.14562, 'liquidity': '2000000'}, {'price': 1.14561, 'liquidity': '5000000'}, {'price': 1.14559, 'liquidity': '10000000'}, {'price': 1.14556, 'liquidity': '10000000'}], 'asks': [{'price': 1.14573, 'liquidity': '400000'}, {'price': 1.14575, 'liquidity': '2500000'}, {'price': 1.14576, 'liquidity': '2000000'}, {'price': 1.14577, 'liquidity': '5000000'}, {'price': 1.1458, 'liquidity': '10000000'}, {'price': 1.14583, 'liquidity': '10000000'}], 'closeoutBid': 1.14556, 'closeoutAsk': 1.14583}, 'reason': 'MARKET_ORDER', 'pl': '-6.0659', 'financing': '0.0', 'commission': '0.0', 'guaranteedExecutionFee': '0.0', 'accountBalance': '202867.917', 'tradesClosed': [{'tradeID': '669', 'units': '-100000.0', 'price': 1.14565, 'realizedPL': '-6.0659', 'financing': '0.0', 'guaranteedExecutionFee': '0.0', 'halfSpreadCost': '3.0178'}], 'halfSpreadCost': '3.0178'}

In [7]:
api.get_account_summary()

{'id': '101-004-36234373-001',
 'alias': 'Primary',
 'currency': 'GBP',
 'balance': '202867.917',
 'createdByUserID': 36234373,
 'createdTime': '2025-08-29T16:11:28.851462359Z',
 'guaranteedStopLossOrderMode': 'ALLOWED',
 'pl': '2839.9212',
 'resettablePL': '2839.9212',
 'resettablePLTime': '0',
 'financing': '27.9958',
 'commission': '0.0',
 'guaranteedExecutionFees': '0.0',
 'marginRate': '0.03333333333333',
 'openTradeCount': 0,
 'openPositionCount': 0,
 'pendingOrderCount': 0,
 'hedgingEnabled': False,
 'unrealizedPL': '0.0',
 'NAV': '202867.917',
 'marginUsed': '0.0',
 'marginAvailable': '202867.917',
 'positionValue': '0.0',
 'marginCloseoutUnrealizedPL': '0.0',
 'marginCloseoutNAV': '202867.917',
 'marginCloseoutMarginUsed': '0.0',
 'marginCloseoutPercent': '0.0',
 'marginCloseoutPositionValue': '0.0',
 'withdrawalLimit': '202867.917',
 'marginCallMarginUsed': '0.0',
 'marginCallPercent': '0.0',
 'lastTransactionID': '671'}

In [8]:
api.get_transactions()

[{'id': '1',
  'time': '2025-08-29T16:11:28.851462359Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '1',
  'requestID': '1610648694742955234',
  'type': 'CREATE',
  'divisionID': 4,
  'siteID': 101,
  'accountUserID': 36234373,
  'accountNumber': 1,
  'homeCurrency': 'GBP'},
 {'id': '2',
  'time': '2025-08-29T16:11:28.851462359Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '1',
  'requestID': '1610648694742955234',
  'type': 'CLIENT_CONFIGURE',
  'alias': 'Primary',
  'marginRate': '0.03333333333333'},
 {'id': '3',
  'time': '2025-08-29T16:11:31.218269202Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '3',
  'requestID': '1610648694755538155',
  'type': 'TRANSFER_FUNDS',
  'amount': '100000.0',
  'fundingReason': 'CLIENT_FUNDING',
  'accountBalance': '100000.0'},
 {'id': '4',
  'time': '2025-08-30T20:37:39.689996369Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '4',
  'requestID': '1754764312194170984',
  'type': 'TRANSFER_FUNDS',
  'amount': '100000.0',
  'fundingReason': 'ADJUSTMENT',
  'accountBalance': '200000.0'},
 {'id': '5',
  'time': '2025-08-30T20:39:27.527611978Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '5',
  'requestID': '97439649773752574',
  'type': 'MARKET_ORDER',
  'instrument': 'EUR_USD',
  'units': '-1000.0',
  'timeInForce': 'FOK',
  'positionFill': 'DEFAULT',
  'reason': 'CLIENT_ORDER'},
 {'id': '6',
  'time': '2025-08-30T20:39:27.527611978Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '5',
  'requestID': '97439649773752574',
  'type': 'ORDER_CANCEL',
  'orderID': '5',
  'reason': 'MARKET_HALTED'},
 {'id': '7',
  'time': '2025-09-01T10:19:14.961216826Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '7',
  'requestID': '97440218469371338',
  'type': 'MARKET_ORDER',
  'instrument': 'EUR_USD',
  'units': '-10000.0',
  'timeInForce': 'FOK',
  'positionFill': 'DEFAULT',
  'reason': 'CLIENT_ORDER'},
 {'id': '8',
  'time': '2025-09-01T10:19:14.961216826Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '7',
  'requestID': '97440218469371338',
  'type': 'ORDER_FILL',
  'orderID': '7',
  'instrument': 'EUR_USD',
  'units': '-10000.0',
  'gainQuoteHomeConversionFactor': '0.735351180002',
  'lossQuoteHomeConversionFactor': '0.742741644123',
  'price': 1.17235,
  'fullVWAP': 1.17235,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 1.17235, 'liquidity': '500000'},
    {'price': 1.17234, 'liquidity': '500000'},
    {'price': 1.17233, 'liquidity': '2000000'},
    {'price': 1.17232, 'liquidity': '2000000'},
    {'price': 1.17231, 'liquidity': '5000000'},
    {'price': 1.17229, 'liquidity': '10000000'},
    {'price': 1.17226, 'liquidity': '10000000'}],
   'asks': [{'price': 1.17242, 'liquidity': '500000'},
    {'price': 1.17244, 'liquidity': '2500000'},
    {'price': 1.17245, 'liquidity': '2000000'},
    {'price': 1.17246, 'liquidity': '5000000'},
    {'price': 1.17249, 'liquidity': '10000000'},
    {'price': 1.17252, 'liquidity': '10000000'}],
   'closeoutBid': 1.17226,
   'closeoutAsk': 1.17252},
  'reason': 'MARKET_ORDER',
  'pl': '0.0',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '200000.0',
  'tradeOpened': {'tradeID': '8',
   'units': '-10000.0',
   'price': 1.17235,
   'guaranteedExecutionFee': '0.0',
   'halfSpreadCost': '0.2587',
   'initialMarginRequired': '288.82'},
  'halfSpreadCost': '0.2587'},
 {'id': '9',
  'time': '2025-09-01T10:38:33.929376904Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '9',
  'requestID': '61411426308251498',
  'type': 'MARKET_ORDER',
  'instrument': 'EUR_USD',
  'units': '10000.0',
  'timeInForce': 'FOK',
  'positionFill': 'REDUCE_ONLY',
  'shortPositionCloseout': {'instrument': 'EUR_USD', 'units': 'ALL'},
  'reason': 'POSITION_CLOSEOUT'},
 {'id': '10',
  'time': '2025-09-01T10:38:33.929376904Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '9',
  'requestID': '61411426308251498',
  'type': 'ORDER_FILL',
  'orderID': '9',
  'instrument': 'EUR_USD',
  'units': '10000.0',
  'gainQuoteHomeConversionFactor': '0.735484351113',
  'lossQuoteHomeConversionFactor': '0.742876153637',
  'price': 1.17233,
  'fullVWAP': 1.17233,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 1.17227, 'liquidity': '500000'},
    {'price': 1.17226, 'liquidity': '500000'},
    {'price': 1.17225, 'liquidity': '2000000'},
    {'price': 1.17224, 'liquidity': '2000000'},
    {'price': 1.17223, 'liquidity': '5000000'},
    {'price': 1.17221, 'liquidity': '10000000'},
    {'price': 1.17218, 'liquidity': '10000000'}],
   'asks': [{'price': 1.17233, 'liquidity': '500000'},
    {'price': 1.17235, 'liquidity': '2500000'},
    {'price': 1.17236, 'liquidity': '2000000'},
    {'price': 1.17237, 'liquidity': '5000000'},
    {'price': 1.1724, 'liquidity': '10000000'},
    {'price': 1.17243, 'liquidity': '10000000'}],
   'closeoutBid': 1.17218,
   'closeoutAsk': 1.17243},
  'reason': 'MARKET_ORDER_POSITION_CLOSEOUT',
  'pl': '0.1471',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '200000.1471',
  'tradesClosed': [{'tradeID': '8',
    'units': '10000.0',
    'price': 1.17233,
    'realizedPL': '0.1471',
    'financing': '0.0',
    'guaranteedExecutionFee': '0.0',
    'halfSpreadCost': '0.2218'}],
  'halfSpreadCost': '0.2218'},
 {'id': '11',
  'time': '2025-09-02T22:16:22.761613556Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '11',
  'requestID': '79426362819454315',
  'type': 'MARKET_ORDER',
  'instrument': 'EUR_USD',
  'units': '100000.0',
  'timeInForce': 'FOK',
  'positionFill': 'DEFAULT',
  'reason': 'CLIENT_ORDER'},
 {'id': '12',
  'time': '2025-09-02T22:16:22.761613556Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '11',
  'requestID': '79426362819454315',
  'type': 'ORDER_FILL',
  'orderID': '11',
  'instrument': 'EUR_USD',
  'units': '100000.0',
  'gainQuoteHomeConversionFactor': '0.742844990773',
  'lossQuoteHomeConversionFactor': '0.750310769574',
  'price': 1.16427,
  'fullVWAP': 1.16427,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 1.1642, 'liquidity': '500000'},
    {'price': 1.16419, 'liquidity': '500000'},
    {'price': 1.16418, 'liquidity': '2000000'},
    {'price': 1.16417, 'liquidity': '2000000'},
    {'price': 1.16416, 'liquidity': '5000000'},
    {'price': 1.16414, 'liquidity': '10000000'},
    {'price': 1.16411, 'liquidity': '10000000'}],
   'asks': [{'price': 1.16427, 'liquidity': '500000'},
    {'price': 1.16429, 'liquidity': '2500000'},
    {'price': 1.1643, 'liquidity': '2000000'},
    {'price': 1.16431, 'liquidity': '5000000'},
    {'price': 1.16434, 'liquidity': '10000000'},
    {'price': 1.16437, 'liquidity': '10000000'}],
   'closeoutBid': 1.16411,
   'closeoutAsk': 1.16437},
  'reason': 'MARKET_ORDER',
  'pl': '0.0',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '200000.1471',
  'tradeOpened': {'tradeID': '12',
   'units': '100000.0',
   'price': 1.16427,
   'guaranteedExecutionFee': '0.0',
   'halfSpreadCost': '2.613',
   'initialMarginRequired': '2897.2'},
  'halfSpreadCost': '2.613'},
 {'id': '13',
  'time': '2025-09-03T10:35:03.088046451Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '13',
  'requestID': '61412150205684323',
  'type': 'MARKET_ORDER',
  'instrument': 'EUR_USD',
  'units': '-100000.0',
  'timeInForce': 'FOK',
  'positionFill': 'REDUCE_ONLY',
  'tradeClose': {'tradeID': '12', 'units': 'ALL'},
  'reason': 'TRADE_CLOSE'},
 {'id': '14',
  'time': '2025-09-03T10:35:03.088046451Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '13',
  'requestID': '61412150205684323',
  'type': 'ORDER_FILL',
  'orderID': '13',
  'instrument': 'EUR_USD',
  'units': '-100000.0',
  'gainQuoteHomeConversionFactor': '0.742050001144',
  'lossQuoteHomeConversionFactor': '0.7495077901',
  'price': 1.16467,
  'fullVWAP': 1.16467,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 1.16467, 'liquidity': '500000'},
    {'price': 1.16466, 'liquidity': '500000'},
    {'price': 1.16465, 'liquidity': '2000000'},
    {'price': 1.16464, 'liquidity': '2000000'},
    {'price': 1.16463, 'liquidity': '5000000'},
    {'price': 1.16461, 'liquidity': '10000000'},
    {'price': 1.16458, 'liquidity': '10000000'}],
   'asks': [{'price': 1.16475, 'liquidity': '500000'},
    {'price': 1.16477, 'liquidity': '2500000'},
    {'price': 1.16478, 'liquidity': '2000000'},
    {'price': 1.16479, 'liquidity': '5000000'},
    {'price': 1.16482, 'liquidity': '10000000'},
    {'price': 1.16485, 'liquidity': '10000000'}],
   'closeoutBid': 1.16458,
   'closeoutAsk': 1.16485},
  'reason': 'MARKET_ORDER_TRADE_CLOSE',
  'pl': '29.682',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '200029.8291',
  'tradesClosed': [{'tradeID': '12',
    'units': '-100000.0',
    'price': 1.16467,
    'realizedPL': '29.682',
    'financing': '0.0',
    'guaranteedExecutionFee': '0.0',
    'halfSpreadCost': '2.9831'}],
  'halfSpreadCost': '2.9831'},
 {'id': '15',
  'time': '2025-09-03T11:40:01.789006126Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '15',
  'requestID': '115455362082579056',
  'type': 'MARKET_ORDER',
  'instrument': 'AUD_JPY',
  'units': '100000.0',
  'timeInForce': 'FOK',
  'positionFill': 'DEFAULT',
  'reason': 'CLIENT_ORDER'},
 {'id': '16',
  'time': '2025-09-03T11:40:01.789006126Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '15',
  'requestID': '115455362082579056',
  'type': 'ORDER_FILL',
  'orderID': '15',
  'instrument': 'AUD_JPY',
  'units': '100000.0',
  'gainQuoteHomeConversionFactor': '0.004993363136',
  'lossQuoteHomeConversionFactor': '0.00504354769',
  'price': 97.148,
  'fullVWAP': 97.148,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 97.125, 'liquidity': '500000'},
    {'price': 97.123, 'liquidity': '500000'},
    {'price': 97.122, 'liquidity': '2000000'},
    {'price': 97.119, 'liquidity': '2000000'},
    {'price': 97.117, 'liquidity': '5000000'},
    {'price': 97.106, 'liquidity': '10000000'},
    {'price': 97.09, 'liquidity': '10000000'},
    {'price': 97.057, 'liquidity': '15000000'}],
   'asks': [{'price': 97.148, 'liquidity': '500000'},
    {'price': 97.151, 'liquidity': '500000'},
    {'price': 97.152, 'liquidity': '2000000'},
    {'price': 97.154, 'liquidity': '2000000'},
    {'price': 97.156, 'liquidity': '5000000'},
    {'price': 97.167, 'liquidity': '10000000'},
    {'price': 97.184, 'liquidity': '10000000'},
    {'price': 97.217, 'liquidity': '15000000'}],
   'closeoutBid': 97.057,
   'closeoutAsk': 97.217},
  'reason': 'MARKET_ORDER',
  'pl': '0.0',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '200029.8291',
  'tradeOpened': {'tradeID': '16',
   'units': '100000.0',
   'price': 97.148,
   'guaranteedExecutionFee': '0.0',
   'halfSpreadCost': '5.7712',
   'initialMarginRequired': '2437.3896'},
  'halfSpreadCost': '5.7712'},
 {'id': '17',
  'time': '2025-09-03T15:30:42.116821430Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '17',
  'requestID': '97441021628206594',
  'type': 'MARKET_ORDER',
  'instrument': 'EUR_USD',
  'units': '100000.0',
  'timeInForce': 'FOK',
  'positionFill': 'DEFAULT',
  'reason': 'CLIENT_ORDER'},
 {'id': '18',
  'time': '2025-09-03T15:30:42.116821430Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '17',
  'requestID': '97441021628206594',
  'type': 'ORDER_FILL',
  'orderID': '17',
  'instrument': 'EUR_USD',
  'units': '100000.0',
  'gainQuoteHomeConversionFactor': '0.739677965401',
  'lossQuoteHomeConversionFactor': '0.747111914802',
  'price': 1.16818,
  'fullVWAP': 1.16818,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 1.1681, 'liquidity': '500000'},
    {'price': 1.16809, 'liquidity': '500000'},
    {'price': 1.16808, 'liquidity': '2000000'},
    {'price': 1.16807, 'liquidity': '2000000'},
    {'price': 1.16806, 'liquidity': '5000000'},
    {'price': 1.16804, 'liquidity': '10000000'},
    {'price': 1.16801, 'liquidity': '10000000'}],
   'asks': [{'price': 1.16818, 'liquidity': '500000'},
    {'price': 1.1682, 'liquidity': '2500000'},
    {'price': 1.16821, 'liquidity': '2000000'},
    {'price': 1.16822, 'liquidity': '5000000'},
    {'price': 1.16825, 'liquidity': '10000000'},
    {'price': 1.16828, 'liquidity': '10000000'}],
   'closeoutBid': 1.16801,
   'closeoutAsk': 1.16828},
  'reason': 'MARKET_ORDER',
  'pl': '0.0',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '200029.8291',
  'tradeOpened': {'tradeID': '18',
   'units': '100000.0',
   'price': 1.16818,
   'guaranteedExecutionFee': '0.0',
   'halfSpreadCost': '2.9736',
   'initialMarginRequired': '2894.6667'},
  'halfSpreadCost': '2.9736'},
 {'id': '19',
  'time': '2025-09-03T21:00:00.000000000Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '19',
  'type': 'DAILY_FINANCING',
  'financing': '-5.2703',
  'accountBalance': '200024.5588',
  'positionFinancings': [{'instrument': 'EUR_USD',
    'financing': '-8.2154',
    'openTradeFinancings': [{'tradeID': '18', 'financing': '-8.2154'}]},
   {'instrument': 'AUD_JPY',
    'financing': '2.9451',
    'openTradeFinancings': [{'tradeID': '16', 'financing': '2.9451'}]}]},
 {'id': '20',
  'time': '2025-09-04T13:43:01.982205945Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '20',
  'requestID': '97441356914125127',
  'type': 'MARKET_ORDER',
  'instrument': 'AUD_JPY',
  'units': '-100000.0',
  'timeInForce': 'FOK',
  'positionFill': 'REDUCE_ONLY',
  'tradeClose': {'tradeID': '16', 'units': 'ALL'},
  'reason': 'TRADE_CLOSE'},
 {'id': '21',
  'time': '2025-09-04T13:43:01.982205945Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '20',
  'requestID': '97441356914125127',
  'type': 'ORDER_FILL',
  'orderID': '20',
  'instrument': 'AUD_JPY',
  'units': '-100000.0',
  'gainQuoteHomeConversionFactor': '0.004984945001',
  'lossQuoteHomeConversionFactor': '0.005035044951',
  'price': 96.87,
  'fullVWAP': 96.87,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 96.87, 'liquidity': '500000'},
    {'price': 96.868, 'liquidity': '500000'},
    {'price': 96.867, 'liquidity': '2000000'},
    {'price': 96.864, 'liquidity': '2000000'},
    {'price': 96.862, 'liquidity': '5000000'},
    {'price': 96.851, 'liquidity': '10000000'},
    {'price': 96.835, 'liquidity': '10000000'},
    {'price': 96.802, 'liquidity': '15000000'}],
   'asks': [{'price': 96.893, 'liquidity': '500000'},
    {'price': 96.896, 'liquidity': '500000'},
    {'price': 96.897, 'liquidity': '2000000'},
    {'price': 96.899, 'liquidity': '2000000'},
    {'price': 96.901, 'liquidity': '5000000'},
    {'price': 96.912, 'liquidity': '10000000'},
    {'price': 96.929, 'liquidity': '10000000'},
    {'price': 96.962, 'liquidity': '15000000'}],
   'closeoutBid': 96.802,
   'closeoutAsk': 96.962},
  'reason': 'MARKET_ORDER_TRADE_CLOSE',
  'pl': '-139.9742',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '199884.5846',
  'tradesClosed': [{'tradeID': '16',
    'units': '-100000.0',
    'price': 96.87,
    'realizedPL': '-139.9742',
    'financing': '0.0',
    'guaranteedExecutionFee': '0.0',
    'halfSpreadCost': '5.7615'}],
  'halfSpreadCost': '5.7615'},
 {'id': '22',
  'time': '2025-09-04T13:57:33.257863660Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '22',
  'requestID': '61412563552969225',
  'type': 'MARKET_ORDER',
  'instrument': 'EUR_JPY',
  'units': '100000.0',
  'timeInForce': 'FOK',
  'positionFill': 'DEFAULT',
  'reason': 'CLIENT_ORDER'},
 {'id': '23',
  'time': '2025-09-04T13:57:33.257863660Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '22',
  'requestID': '61412563552969225',
  'type': 'ORDER_FILL',
  'orderID': '22',
  'instrument': 'EUR_JPY',
  'units': '100000.0',
  'gainQuoteHomeConversionFactor': '0.004987131235',
  'lossQuoteHomeConversionFactor': '0.005037253157',
  'price': 172.96,
  'fullVWAP': 172.96,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 172.933, 'liquidity': '500000'},
    {'price': 172.93, 'liquidity': '500000'},
    {'price': 172.929, 'liquidity': '2000000'},
    {'price': 172.927, 'liquidity': '2000000'},
    {'price': 172.923, 'liquidity': '5000000'},
    {'price': 172.919, 'liquidity': '10000000'},
    {'price': 172.913, 'liquidity': '10000000'}],
   'asks': [{'price': 172.96, 'liquidity': '500000'},
    {'price': 172.963, 'liquidity': '500000'},
    {'price': 172.964, 'liquidity': '2000000'},
    {'price': 172.967, 'liquidity': '2000000'},
    {'price': 172.97, 'liquidity': '5000000'},
    {'price': 172.975, 'liquidity': '10000000'},
    {'price': 172.98, 'liquidity': '10000000'}],
   'closeoutBid': 172.913,
   'closeoutAsk': 172.98},
  'reason': 'MARKET_ORDER',
  'pl': '0.0',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '199884.5846',
  'tradeOpened': {'tradeID': '23',
   'units': '100000.0',
   'price': 172.96,
   'guaranteedExecutionFee': '0.0',
   'halfSpreadCost': '6.7665',
   'initialMarginRequired': '2889.4333'},
  'halfSpreadCost': '6.7665'},
 {'id': '24',
  'time': '2025-09-04T13:57:43.592102737Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '24',
  'requestID': '79426962104023802',
  'type': 'MARKET_ORDER',
  'instrument': 'EUR_USD',
  'units': '-100000.0',
  'timeInForce': 'FOK',
  'positionFill': 'REDUCE_ONLY',
  'tradeClose': {'tradeID': '18', 'units': 'ALL'},
  'reason': 'TRADE_CLOSE'},
 {'id': '25',
  'time': '2025-09-04T13:57:43.592102737Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '24',
  'requestID': '79426962104023802',
  'type': 'ORDER_FILL',
  'orderID': '24',
  'instrument': 'EUR_USD',
  'units': '-100000.0',
  'gainQuoteHomeConversionFactor': '0.740269550354',
  'lossQuoteHomeConversionFactor': '0.747709445333',
  'price': 1.16504,
  'fullVWAP': 1.16504,
  'fullPrice': {'type': 'PRICE',
   'bids': [{'price': 1.16504, 'liquidity': '500000'},
    {'price': 1.16503, 'liquidity': '500000'},
    {'price': 1.16502, 'liquidity': '2000000'},
    {'price': 1.16501, 'liquidity': '2000000'},
    {'price': 1.165, 'liquidity': '5000000'},
    {'price': 1.16498, 'liquidity': '10000000'},
    {'price': 1.16495, 'liquidity': '10000000'}],
   'asks': [{'price': 1.16513, 'liquidity': '500000'},
    {'price': 1.16515, 'liquidity': '2500000'},
    {'price': 1.16516, 'liquidity': '2000000'},
    {'price': 1.16517, 'liquidity': '5000000'},
    {'price': 1.1652, 'liquidity': '10000000'},
    {'price': 1.16523, 'liquidity': '10000000'}],
   'closeoutBid': 1.16495,
   'closeoutAsk': 1.16523},
  'reason': 'MARKET_ORDER_TRADE_CLOSE',
  'pl': '-234.7808',
  'financing': '0.0',
  'commission': '0.0',
  'guaranteedExecutionFee': '0.0',
  'accountBalance': '199649.8038',
  'tradesClosed': [{'tradeID': '18',
    'units': '-100000.0',
    'price': 1.16504,
    'realizedPL': '-234.7808',
    'financing': '0.0',
    'guaranteedExecutionFee': '0.0',
    'halfSpreadCost': '3.348'}],
  'halfSpreadCost': '3.348'},
 {'id': '26',
  'time': '2025-09-04T21:00:00.000000000Z',
  'userID': 36234373,
  'accountID': '101-004-36234373-001',
  'batchID': '26',
  'type': 'DAILY_FINANCING',
  'financing': '1.3473',
  'accountBalance': '199651.1511',
  'positionFinancings': [{'instrument': 'EUR_JPY',
    'financing': '1.3473',
    'openTradeFinancings': [{'tradeID': '23', 'financing': '1.3473'}]}]},
 {'id': '27',

In [9]:
api.print_transactions()

   8 | 2025-09-01T10:19:14.96 | EUR_USD | -10000.0 |      0.0
  10 | 2025-09-01T10:38:33.92 | EUR_USD |  10000.0 |   0.1471
  12 | 2025-09-02T22:16:22.76 | EUR_USD | 100000.0 |      0.0
  14 | 2025-09-03T10:35:03.08 | EUR_USD | -100000.0 |   29.682
  16 | 2025-09-03T11:40:01.78 | AUD_JPY | 100000.0 |      0.0
  18 | 2025-09-03T15:30:42.11 | EUR_USD | 100000.0 |      0.0
  21 | 2025-09-04T13:43:01.98 | AUD_JPY | -100000.0 | -139.9742
  23 | 2025-09-04T13:57:33.25 | EUR_JPY | 100000.0 |      0.0
  25 | 2025-09-04T13:57:43.59 | EUR_USD | -100000.0 | -234.7808
  33 | 2025-09-07T21:04:55.06 | EUR_JPY | -100000.0 | 265.8458
  35 | 2025-09-08T13:38:18.35 | EUR_USD | 100000.0 |      0.0
  38 | 2025-09-08T13:40:27.55 | EUR_USD | -100000.0 |   3.6709
  41 | 2025-09-08T13:57:57.79 | EUR_USD | -100000.0 |      0.0
  43 | 2025-09-08T14:19:27.38 | EUR_USD | 100000.0 |  55.1379
  45 | 2025-09-08T14:36:13.37 | EUR_USD | 100000.0 |      0.0
  47 | 2025-09-08T16:54:01.00 | EUR_USD | -100000.0 | -66.0869
  49 | 2025-09-23T16:40:00.26 | EUR_USD | -100000.0 |      0.0
  51 | 2025-09-23T16:40:03.99 | EUR_USD | 100000.0 |    13.25
  53 | 2025-09-23T17:22:00.32 | EUR_USD | -100000.0 |      0.0
  56 | 2025-09-24T13:12:44.12 | EUR_USD | 100000.0 |  502.112
  58 | 2025-09-24T15:23:47.25 | EUR_USD | 100000.0 |      0.0
  60 | 2025-09-24T15:23:47.98 | EUR_USD | -100000.0 |  -8.2162
  62 | 2025-09-24T15:23:48.73 | EUR_USD | 100000.0 |      0.0
  64 | 2025-09-24T15:23:48.90 | EUR_USD | -100000.0 |  -5.9753
  66 | 2025-09-24T15:24:02.03 | EUR_USD | -100000.0 |      0.0
  68 | 2025-09-24T15:26:00.35 | EUR_USD | 200000.0 |  -5.9758
  70 | 2025-09-24T15:26:38.84 | EUR_USD | -100000.0 | -11.2049
  72 | 2025-09-24T15:27:00.41 | EUR_USD | -100000.0 |      0.0
  74 | 2025-09-24T15:29:17.38 | EUR_USD | 100000.0 |   5.9168
  76 | 2025-10-14T16:25:32.72 | EUR_USD | 100000.0 |      0.0
  78 | 2025-10-14T16:25:33.03 | EUR_USD | -100000.0 |  -5.2847
  80 | 2025-10-14T16:25:34.66 | EUR_USD | 100000.0 |      0.0
  82 | 2025-10-14T16:25:34.84 | EUR_USD | -100000.0 |  -5.2847
  84 | 2025-10-14T16:27:00.83 | EUR_USD | -100000.0 |      0.0
  86 | 2025-10-14T16:28:21.00 | EUR_USD | 100000.0 |   -6.795
  88 | 2025-10-14T16:55:00.48 | EUR_USD | 100000.0 |      0.0
  90 | 2025-10-14T16:56:02.19 | EUR_USD | -100000.0 |   6.7225
  92 | 2025-10-14T17:01:00.21 | EUR_USD | -100000.0 |      0.0
  94 | 2025-10-14T17:01:37.63 | EUR_USD | 100000.0 | -12.8273
  96 | 2025-10-14T17:17:01.99 | EUR_USD | 100000.0 |      0.0
  98 | 2025-10-14T17:18:06.18 | EUR_USD | -100000.0 |  -6.0367
 100 | 2025-10-14T17:21:00.33 | EUR_USD | -100000.0 |      0.0
 102 | 2025-10-14T17:21:36.03 | EUR_USD | 100000.0 |  -3.7741
 104 | 2025-10-16T23:36:00.78 | EUR_USD | -100000.0 |      0.0
 106 | 2025-10-16T23:37:04.58 | EUR_USD | 200000.0 |   4.4415
 108 | 2025-10-16T23:39:45.79 | EUR_USD | -100000.0 |      0.0
 110 | 2025-10-20T23:40:00.66 | EUR_USD | -100000.0 |      0.0
 112 | 2025-10-20T23:41:03.21 | EUR_USD | 200000.0 |   -2.999
 114 | 2025-10-20T23:43:13.52 | EUR_USD | -200000.0 |  -8.2475
 116 | 2025-10-20T23:45:00.29 | EUR_USD | 200000.0 |  -8.2475
 118 | 2025-10-20T23:45:15.92 | EUR_USD | -100000.0 |  -7.4977
 120 | 2025-10-20T23:46:17.27 | EUR_USD | -100000.0 |      0.0
 122 | 2025-10-20T23:47:04.98 | EUR_USD | 100000.0 |   -8.247
 124 | 2025-10-20T23:48:09.28 | EUR_USD | -100000.0 |      0.0
 126 | 2025-10-20T23:49:06.77 | EUR_USD | 200000.0 |  -7.4976
 128 | 2025-10-20T23:50:17.10 | EUR_USD | -100000.0 |  -8.9972
 130 | 2025-10-22T16:39:00.48 | EUR_USD | -100000.0 |      0.0
 132 | 2025-10-22T16:39:58.72 | EUR_USD | 100000.0 |   0.7439
 134 | 2025-10-22T19:11:08.15 | EUR_USD | -100000.0 |      0.0
 136 | 2025-10-22T19:12:45.49 | EUR_USD | 100000.0 | -10.5331
 138 | 2025-10-24T06:45:00.95 | EUR_USD | -100000.0 |      0.0
 140 | 2025-10-24T06:46:01.27 | EUR_USD | 200000.0 |   -2.262
 142 | 2025-10-24T06:46:12.22 | EUR_USD | -100000.0 |  -4.5242
 144 | 2025-11-21T10:02:24.81 | EUR_USD |  -1000.0 |      0.0
 159 | 2025-12-04T10:55:27.23 | EUR_USD |   1000.0 | -10.5331
 161 | 2025-12-05T12:06:56.32 | EUR_USD |   1000.0 |      0.0
 164 | 2025-12-05T12:09:10.96 | EUR_USD |  -1000.0 |  -0.2034
 167 | 2025-12-10T14:10:21.53 | EUR_USD | 100000.0 |      0.0
 169 | 2025-12-10T14:10:43.75 | EUR_USD | -100000.0 |  -7.5401
 171 | 2025-12-10T14:12:59.29 | EUR_USD | 100000.0 |      0.0
 173 | 2025-12-10T14:13:32.59 | EUR_USD | -100000.0 | -19.6055
 175 | 2025-12-15T20:47:02.51 | EUR_USD |   1000.0 |      0.0
 177 | 2025-12-15T20:48:05.73 | EUR_USD |  -2000.0 |  -0.1127
 179 | 2025-12-15T20:52:00.57 | EUR_USD |   2000.0 |  -0.0376
 184 | 2025-12-18T16:27:00.72 | EUR_USD |  -1000.0 |  -0.8026
 186 | 2025-12-18T16:43:04.04 | EUR_USD |   1000.0 |      0.0
 188 | 2025-12-18T16:48:00.42 | EUR_USD |  -1000.0 |  -0.3153
 190 | 2025-12-18T16:55:00.68 | EUR_USD |   1000.0 |      0.0
 192 | 2025-12-18T16:56:00.64 | EUR_USD |  -1000.0 |  -0.0676
 194 | 2025-12-18T16:57:00.54 | EUR_USD |  -1000.0 |      0.0
 196 | 2025-12-18T16:58:00.93 | EUR_USD |   1000.0 |  -0.0901
 198 | 2025-12-18T17:00:00.66 | EUR_USD |   1000.0 |      0.0
 200 | 2025-12-18T17:06:00.33 | EUR_USD |  -1000.0 |  -0.4132
 202 | 2025-12-18T17:07:00.31 | EUR_USD |   1000.0 |      0.0
 204 | 2025-12-18T18:05:00.59 | EUR_USD | -100000.0 |  -0.2554
 206 | 2025-12-18T18:10:05.00 | EUR_USD | 100000.0 | -34.9506
 208 | 2025-12-18T18:24:08.96 | EUR_USD |  -1000.0 |  -0.4508
 210 | 2025-12-18T18:25:00.21 | EUR_USD |   2000.0 |      0.0
 212 | 2025-12-18T18:34:00.78 | EUR_USD |  -2000.0 |   0.2231
 223 | 2025-12-18T18:44:01.44 | EUR_USD | 100000.0 |      0.0
 225 | 2025-12-18T18:46:00.39 | EUR_USD | -200000.0 |  -7.5097
 227 | 2025-12-18T18:46:47.20 | EUR_USD | 100000.0 |   -3.004
 229 | 2025-12-18T18:48:06.84 | EUR_USD | 100000.0 |      0.0
 231 | 2025-12-18T18:50:21.82 | EUR_USD | -100000.0 | -16.5245
 233 | 2025-12-18T18:52:01.42 | EUR_USD | -100000.0 |      0.0
 235 | 2025-12-18T18:53:04.30 | EUR_USD | 200000.0 |  -5.2574
 237 | 2025-12-18T18:54:01.40 | EUR_USD | -200000.0 |  -6.0087
 239 | 2025-12-18T18:58:00.98 | EUR_USD | 100000.0 | -13.5166
 241 | 2025-12-18T18:59:00.38 | EUR_USD | 100000.0 |      0.0
 244 | 2025-12-18T22:41:00.38 | EUR_USD | -100000.0 |  19.3312
 246 | 2025-12-18T23:01:07.05 | EUR_USD | 200000.0 |      0.0
 248 | 2025-12-18T23:20:08.26 | EUR_USD | 100000.0 |      0.0
 250 | 2025-12-19T11:09:00.36 | EUR_USD | 100000.0 |      0.0
 252 | 2025-12-19T11:14:22.99 | EUR_USD | -100000.0 | -111.9484
 254 | 2025-12-19T11:15:32.57 | EUR_USD | -300000.0 | -339.7353
 256 | 2025-12-19T12:12:00.40 | EUR_USD | -100000.0 |      0.0
 258 | 2025-12-19T12:16:03.26 | EUR_USD | 100000.0 | -22.5466
 260 | 2025-12-19T12:17:03.14 | EUR_USD | -100000.0 |      0.0
 262 | 2025-12-19T12:21:00.92 | EUR_USD | 100000.0 |  16.3724
 264 | 2025-12-19T12:24:39.18 | EUR_USD | -100000.0 |      0.0
 266 | 2025-12-19T12:28:00.29 | EUR_USD | -100000.0 |      0.0
 268 | 2025-12-19T12:47:41.20 | EUR_USD | 200000.0 | -76.6224
 270 | 2025-12-19T12:48:00.46 | EUR_USD | -100000.0 |      0.0
 272 | 2025-12-19T12:54:00.62 | EUR_USD | 100000.0 |  23.0654
 274 | 2025-12-19T12:56:00.92 | EUR_USD | 100000.0 |      0.0
 276 | 2025-12-19T12:59:52.93 | EUR_USD | -100000.0 |  -9.0182
 278 | 2025-12-19T15:04:01.00 | EUR_USD | -100000.0 |      0.0
 280 | 2025-12-19T15:09:47.14 | EUR_USD | 100000.0 |   0.7441
 282 | 2025-12-23T11:36:04.47 | EUR_USD | 100000.0 |      0.0
 284 | 2025-12-23T11:38:01.51 | EUR_USD | -200000.0 |   -5.207
 286 | 2025-12-23T11:39:02.68 | EUR_USD | 100000.0 |  -5.9518
 288 | 2025-12-23T11:40:01.08 | EUR_USD | -100000.0 |      0.0
 290 | 2025-12-23T11:42:02.06 | EUR_USD | 200000.0 |  -5.9505
 292 | 2025-12-23T11:44:00.70 | EUR_USD | -200000.0 |  -2.9756
 294 | 2025-12-23T11:46:00.31 | EUR_USD | 200000.0 |  -0.7441
 296 | 2025-12-23T11:46:38.86 | EUR_USD | -100000.0 |  -2.2319
 298 | 2025-12-23T11:57:05.50 | EUR_USD | 100000.0 |      0.0
 300 | 2025-12-23T11:58:00.67 | EUR_USD | -200000.0 |   6.6309
 302 | 2025-12-23T12:04:03.90 | EUR_USD | 200000.0 | -30.5097
 304 | 2025-12-23T12:05:04.32 | EUR_USD | -200000.0 |  -6.6968
 306 | 2025-12-23T12:06:36.74 | EUR_USD | 100000.0 |   -2.232
 308 | 2026-01-07T09:23:33.19 | EUR_USD | 100000.0 |      0.0
 312 | 2026-01-09T20:35:02.49 | EUR_USD | -100000.0 | -356.0189
 314 | 2026-01-26T10:45:08.17 | EUR_USD | -100000.0 |      0.0
 316 | 2026-01-26T11:07:50.36 | EUR_USD | 100000.0 |  28.3877
 318 | 2026-01-26T11:14:00.52 | EUR_USD | -100000.0 |      0.0
 320 | 2026-01-26T11:36:00.53 | EUR_USD | -100000.0 |      0.0
 322 | 2026-01-26T11:46:02.58 | EUR_USD | -100000.0 |      0.0
 324 | 2026-01-26T11:53:01.77 | EUR_USD | -100000.0 |      0.0
 326 | 2026-01-26T11:53:51.69 | EUR_USD | 400000.0 | -101.4491
 328 | 2026-01-26T11:58:00.77 | EUR_USD | -100000.0 |      0.0
 330 | 2026-01-26T12:00:42.18 | EUR_USD | 100000.0 |   7.2802
 332 | 2026-01-26T12:01:00.48 | EUR_USD | -100000.0 |      0.0
 334 | 2026-01-26T12:09:00.50 | EUR_USD | -200000.0 |      0.0
 336 | 2026-01-26T12:10:00.34 | EUR_USD | -200000.0 |      0.0
 338 | 2026-01-26T12:10:21.69 | EUR_USD | 500000.0 | -25.0091
 340 | 2026-01-26T12:11:00.57 | EUR_USD | -100000.0 |      0.0
 342 | 2026-01-26T12:12:00.89 | EUR_USD | -200000.0 |      0.0
 344 | 2026-01-26T12:13:01.96 | EUR_USD | -200000.0 |      0.0
 346 | 2026-01-26T12:14:00.78 | EUR_USD | -200000.0 |      0.0
 348 | 2026-01-26T12:15:00.40 | EUR_USD | -200000.0 |      0.0
 350 | 2026-01-26T12:15:40.84 | EUR_USD | 900000.0 | -28.6936
 352 | 2026-01-26T12:26:01.74 | EUR_USD | 100000.0 |      0.0
 354 | 2026-01-26T13:00:00.37 | EUR_USD | -200000.0 | -50.7907
 356 | 2026-01-26T13:01:02.64 | EUR_USD | -200000.0 |      0.0
 358 | 2026-01-26T13:14:01.90 | EUR_USD | -200000.0 |      0.0
 360 | 2026-01-26T13:20:00.53 | EUR_USD | -200000.0 |      0.0
 362 | 2026-01-26T13:21:01.29 | EUR_USD | -200000.0 |      0.0
 364 | 2026-01-26T13:25:02.40 | EUR_USD | -200000.0 |      0.0
 366 | 2026-01-26T13:26:00.35 | EUR_USD | -200000.0 |      0.0
 368 | 2026-01-26T13:27:00.46 | EUR_USD | -200000.0 |      0.0
 370 | 2026-01-26T13:29:03.63 | EUR_USD | -200000.0 |      0.0
 372 | 2026-01-26T13:33:00.58 | EUR_USD | -200000.0 |      0.0
 374 | 2026-01-26T13:38:09.54 | EUR_USD | 1900000.0 | -607.3643
 376 | 2026-01-27T01:41:00.54 | EUR_USD |  -1000.0 |      0.0
 378 | 2026-01-27T01:42:01.25 | EUR_USD |  -2000.0 |      0.0
 380 | 2026-01-27T01:43:00.79 | EUR_USD |  -2000.0 |      0.0
 382 | 2026-01-27T01:44:01.73 | EUR_USD |  -6000.0 |      0.0
 384 | 2026-01-27T01:45:00.59 | EUR_USD |  -6000.0 |      0.0
 386 | 2026-01-27T01:46:03.69 | EUR_USD |  -6000.0 |      0.0
 388 | 2026-01-27T01:47:03.81 | EUR_USD |  -6000.0 |      0.0
 390 | 2026-01-27T01:48:02.07 | EUR_USD |  -6000.0 |      0.0
 392 | 2026-01-27T01:49:00.43 | EUR_USD |  -6000.0 |      0.0
 394 | 2026-01-27T01:50:05.16 | EUR_USD |  -6000.0 |      0.0
 396 | 2026-01-27T01:51:00.84 | EUR_USD |  -6000.0 |      0.0
 398 | 2026-01-27T01:52:02.27 | EUR_USD |  -6000.0 |      0.0
 400 | 2026-01-27T01:53:01.92 | EUR_USD |  -6000.0 |      0.0
 402 | 2026-01-27T01:54:01.80 | EUR_USD |  -6000.0 |      0.0
 404 | 2026-01-27T01:55:00.45 | EUR_USD |  -6000.0 |      0.0
 406 | 2026-01-27T01:56:01.51 | EUR_USD |  -6000.0 |      0.0
 408 | 2026-01-27T01:57:02.17 | EUR_USD |  -6000.0 |      0.0
 410 | 2026-01-27T01:58:01.07 | EUR_USD |  -6000.0 |      0.0
 412 | 2026-01-27T01:59:01.14 | EUR_USD |  -6000.0 |      0.0
 414 | 2026-01-27T02:00:01.10 | EUR_USD |  -6000.0 |      0.0
 416 | 2026-01-27T02:01:00.45 | EUR_USD |  -6000.0 |      0.0
 418 | 2026-01-27T02:02:02.35 | EUR_USD |  -6000.0 |      0.0
 420 | 2026-01-27T02:03:05.26 | EUR_USD |  -6000.0 |      0.0
 422 | 2026-01-27T02:04:02.78 | EUR_USD |  -6000.0 |      0.0
 424 | 2026-01-27T02:05:00.91 | EUR_USD |  -6000.0 |      0.0
 426 | 2026-01-27T02:06:02.50 | EUR_USD |  -6000.0 |      0.0
 428 | 2026-01-27T02:07:01.18 | EUR_USD |  -6000.0 |      0.0
 430 | 2026-01-27T02:08:00.33 | EUR_USD |  -6000.0 |      0.0
 432 | 2026-01-27T02:09:01.45 | EUR_USD |  -6000.0 |      0.0
 434 | 2026-01-27T02:10:00.43 | EUR_USD |  -6000.0 |      0.0
 436 | 2026-01-27T02:11:00.80 | EUR_USD |  -6000.0 |      0.0
 438 | 2026-01-27T02:12:04.70 | EUR_USD |  -6000.0 |      0.0
 440 | 2026-01-27T02:17:02.13 | EUR_USD | -200000.0 |      0.0
 442 | 2026-01-27T02:18:10.01 | EUR_USD | -200000.0 |      0.0
 444 | 2026-01-27T02:19:12.86 | EUR_USD | -200000.0 |      0.0
 446 | 2026-01-27T02:20:11.27 | EUR_USD | -200000.0 |      0.0
 448 | 2026-01-27T02:21:01.02 | EUR_USD | -200000.0 |      0.0
 450 | 2026-01-27T02:22:02.20 | EUR_USD | -200000.0 |      0.0
 452 | 2026-01-27T02:23:03.45 | EUR_USD | -200000.0 |      0.0
 454 | 2026-01-27T02:24:03.28 | EUR_USD | -200000.0 |      0.0
 456 | 2026-01-27T02:25:01.82 | EUR_USD | -200000.0 |      0.0
 458 | 2026-01-27T02:26:00.89 | EUR_USD | -200000.0 |      0.0
 460 | 2026-01-27T02:27:00.70 | EUR_USD | -200000.0 |      0.0
 462 | 2026-01-27T02:28:11.86 | EUR_USD | -200000.0 |      0.0
 464 | 2026-01-27T02:29:02.06 | EUR_USD | -200000.0 |      0.0
 466 | 2026-01-27T02:30:00.48 | EUR_USD | -200000.0 |      0.0
 468 | 2026-01-27T02:30:00.77 | EUR_USD | -200000.0 |      0.0
 470 | 2026-01-27T02:31:00.63 | EUR_USD | -200000.0 |      0.0
 472 | 2026-01-27T02:31:00.80 | EUR_USD | -200000.0 |      0.0
 474 | 2026-01-27T02:32:00.32 | EUR_USD | -200000.0 |      0.0
 476 | 2026-01-27T02:33:00.78 | EUR_USD | -200000.0 |      0.0
 478 | 2026-01-27T02:33:01.21 | EUR_USD | -200000.0 |      0.0
 480 | 2026-01-27T02:34:00.70 | EUR_USD | -200000.0 |      0.0
 482 | 2026-01-27T02:35:00.58 | EUR_USD | -200000.0 |      0.0
 484 | 2026-01-27T02:36:00.34 | EUR_USD | -200000.0 |      0.0
 486 | 2026-01-27T02:36:00.42 | EUR_USD | -200000.0 |      0.0
 488 | 2026-01-27T02:37:01.27 | EUR_USD | -200000.0 |      0.0
 490 | 2026-01-27T02:37:01.35 | EUR_USD | -200000.0 |      0.0
 492 | 2026-01-27T02:38:04.03 | EUR_USD | -200000.0 |      0.0
 494 | 2026-01-27T02:38:04.33 | EUR_USD | -200000.0 |      0.0
 496 | 2026-01-27T02:39:00.94 | EUR_USD | -200000.0 |      0.0
 498 | 2026-01-27T02:40:01.20 | EUR_USD | -200000.0 |      0.0
 500 | 2026-01-27T02:40:01.26 | EUR_USD | -200000.0 |      0.0
 502 | 2026-01-27T02:41:00.86 | EUR_USD | -200000.0 |      0.0
 560 | 2026-01-27T03:01:00.58 | EUR_USD | -200000.0 |      0.0
 603 | 2026-01-27T03:21:55.95 | EUR_USD | 6779000.0 |  259.081
 605 | 2026-01-27T10:18:00.58 | EUR_USD | 100000.0 |      0.0
 609 | 2026-01-28T10:53:05.67 | EUR_USD | -100000.0 | 805.5863
 611 | 2026-01-28T10:54:01.67 | EUR_USD | 100000.0 |      0.0
 613 | 2026-01-28T13:33:00.68 | EUR_USD | -200000.0 | -175.7682
 651 | 2026-03-05T13:59:39.63 | XAU_GBP |   -500.0 |      0.0
 653 | 2026-03-05T14:00:43.85 | XAU_GBP |    500.0 |   -221.5
 663 | 2026-03-13T14:39:46.71 | EUR_USD | 100000.0 | 3692.833
 665 | 2026-03-13T14:40:14.77 | EUR_USD | -100000.0 |      0.0
 667 | 2026-03-13T14:41:46.96 | EUR_USD | 100000.0 |  -3.7861
 669 | 2026-03-13T15:04:21.75 | EUR_USD | 100000.0 |      0.0
 671 | 2026-03-13T15:04:22.06 | EUR_USD | -100000.0 |  -6.0659

In [10]:
order = api.create_order("EUR_USD", 100000, suppress=True, ret=True)

In [11]:
order

{'id': '673',
 'time': '2026-03-13T15:04:24.115536039Z',
 'userID': 36234373,
 'accountID': '101-004-36234373-001',
 'batchID': '672',
 'requestID': '115524629598104707',
 'type': 'ORDER_FILL',
 'orderID': '672',
 'instrument': 'EUR_USD',
 'units': '100000.0',
 'gainQuoteHomeConversionFactor': '0.750699777177',
 'lossQuoteHomeConversionFactor': '0.758244498556',
 'price': 1.14573,
 'fullVWAP': 1.14573,
 'fullPrice': {'type': 'PRICE',
  'bids': [{'price': 1.14564, 'liquidity': '400000'},
   {'price': 1.14563, 'liquidity': '500000'},
   {'price': 1.14562, 'liquidity': '2000000'},
   {'price': 1.14561, 'liquidity': '2000000'},
   {'price': 1.1456, 'liquidity': '5000000'},
   {'price': 1.14558, 'liquidity': '10000000'},
   {'price': 1.14555, 'liquidity': '10000000'}],
  'asks': [{'price': 1.14573, 'liquidity': '400000'},
   {'price': 1.14575, 'liquidity': '2500000'},
   {'price': 1.14576, 'liquidity': '2000000'},
   {'price': 1.14577, 'liquidity': '5000000'},
   {'price': 1.1458, 'liquidity': '10000000'},
   {'price': 1.14583, 'liquidity': '10000000'}],
  'closeoutBid': 1.14555,
  'closeoutAsk': 1.14583},
 'reason': 'MARKET_ORDER',
 'pl': '0.0',
 'financing': '0.0',
 'commission': '0.0',
 'guaranteedExecutionFee': '0.0',
 'accountBalance': '202867.917',
 'tradeOpened': {'tradeID': '673',
  'units': '100000.0',
  'price': 1.14573,
  'guaranteedExecutionFee': '0.0',
  'halfSpreadCost': '3.3951',
  'initialMarginRequired': '2881.3333'},
 'halfSpreadCost': '3.3951'}

In [12]:
order['price']

1.14573

In [13]:
order['time']

'2026-03-13T15:04:24.115536039Z'

**Trader class in live action**

In [14]:
from datetime import datetime, timedelta
import time

Storing and resampling real-time tick data

In [45]:
class GetTickData(tpqoa.tpqoa):
    
    def __init__(self, conf_file, instrument, bar_length):
        super().__init__(conf_file)
        self.instrument = instrument 
        self.bar_length = bar_length
        self.tick_data = pd.DataFrame()
        self.last_bar = pd.Timestamp.now(tz='UTC').floor(self.bar_length) #Initialize last bar time to the most recent bar boundary
        
    def on_success(self, time, bid, ask):
        print(self.ticks, end=" ")
        
        #collect and store tick data
        recent_tick = pd.to_datetime(time) #Pandas timestamp object
        df = pd.DataFrame({ "bid": [bid], "ask": [ask], "mid": [(bid + ask) / 2] }, index=[recent_tick])
    
        self.tick_data = pd.concat([self.tick_data, df])
        
        #If time longer than the bar length has passed since the last bar, resample and join the data
        if recent_tick - self.last_bar >= pd.Timedelta(self.bar_length):
            self.resample_and_join()    
        
    def resample_and_join(self):
        self.data = self.tick_data.resample(self.bar_length, label='right').last().ffill().iloc[:-1]
        self.last_bar = self.data.index[-1] #Update the time of the last bar

In [46]:
td = GetTickData("D:\\Dissertation Mohit\\src\\oanda.cfg","EUR_USD", "5s")

In [47]:
td.stream_data("EUR_USD", stop=20)

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

In [48]:
td.tick_data

                                         bid      ask       mid
2026-03-13 15:28:27.396388440+00:00  1.14498  1.14506  1.145020
2026-03-13 15:28:27.932902344+00:00  1.14498  1.14506  1.145020
2026-03-13 15:28:28.039519455+00:00  1.14497  1.14506  1.145015
2026-03-13 15:28:28.472349677+00:00  1.14497  1.14506  1.145015
2026-03-13 15:28:28.675319869+00:00  1.14498  1.14507  1.145025
2026-03-13 15:28:29.125624818+00:00  1.14499  1.14506  1.145025
2026-03-13 15:28:29.776344285+00:00  1.14497  1.14505  1.145010
2026-03-13 15:28:29.803402886+00:00  1.14496  1.14505  1.145005
2026-03-13 15:28:31.029520066+00:00  1.14496  1.14505  1.145005
2026-03-13 15:28:31.148336064+00:00  1.14500  1.14508  1.145040
2026-03-13 15:28:32.084883125+00:00  1.14496  1.14506  1.145010
2026-03-13 15:28:32.359554929+00:00  1.14496  1.14505  1.145005
2026-03-13 15:28:32.700036421+00:00  1.14497  1.14505  1.145010
2026-03-13 15:28:32.992855131+00:00  1.14496  1.14505  1.145005
2026-03-13 15:28:33.589733667+00:00  1.14496  1.14506  1.145010
2026-03-13 15:28:34.342462794+00:00  1.14496  1.14504  1.145000
2026-03-13 15:28:34.621284505+00:00  1.14496  1.14503  1.144995
2026-03-13 15:28:34.926630349+00:00  1.14496  1.14503  1.144995
2026-03-13 15:28:36.415869729+00:00  1.14497  1.14504  1.145005
2026-03-13 15:28:37.608797591+00:00  1.14499  1.14507  1.145030

In [49]:
td.data

                               bid      ask       mid
2026-03-13 15:28:30+00:00  1.14496  1.14505  1.145005
2026-03-13 15:28:35+00:00  1.14496  1.14503  1.144995